"use client";

import Link from "next/link";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useUser } from "@clerk/nextjs";
import { TwitterTweetEmbed } from 'react-twitter-embed';
import ImageCarousel from "./components/ImageCarousel";

// Component for rendering a subscription plan card
const SubscriptionPlan = ({
  title,
  price,
  features,
  link,
  userId,
  userEmail,
  yearly,
  className, // Added className prop for custom styling
}) => {
  // Append user metadata to the payment link
  const paymentLinkWithMetadata = `${link}?client_reference_id=${userId}&prefilled_email=${encodeURIComponent(
    userEmail
  )}`;

  return (
    <div className={`bg-white p-6 rounded-lg shadow-md ${className}`}>
      <h3 className="text-xl font-bold mb-2 text-center">{title}</h3>
      <p className="text-2xl font-bold mb-4 text-center">
        ${price}
        <span className="text-sm font-normal">{yearly ? "" : "/mo"}</span>
      </p>
      <Link
        href={paymentLinkWithMetadata}
        className="bg-black hover:bg-gray-800 text-white font-bold py-2 px-6 rounded-full transition-colors duration-200 inline-block"
      >
        Subscribe →
      </Link>
      <ul className="text-center space-y-2 text-base">
        {features.map((feature, index) => (
          <li key={index} className="flex items-center justify-center">
            <span className="text-green-500 mr-2 text-lg">✓</span>
            <span>{feature}</span>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default function LandingPage() {
  const { user, isLoaded } = useUser();
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted || !isLoaded) return null;

  const userEmail = user?.primaryEmailAddress?.emailAddress || "";

  return (
    <div className="flex flex-col min-h-screen">
      {/* Hero Section with Carousel */}
      <section className="relative flex flex-col items-center justify-center px-6 h-screen bg-transparent">
        <div className="absolute inset-0">
          <ImageCarousel />
        </div>
        <div className="w-full md:w-3/4 max-w-4xl text-center relative z-20 bg-white bg-opacity-90 p-8 rounded-lg shadow-lg">
          <h1 className="text-4xl md:text-5xl font-bold mb-6 text-black">
            Throw away your Camera – Let AI Capture Your World!
          </h1>
          <p className="text-lg md:text-xl mb-6 text-black">
            Revolutionize your memories with Photogen, powered by state-of-the-art models and crafted by two AI enthusiasts. Say goodbye to tedious photo shoots and hello to breathtaking images and videos, all generated by AI right from your device.
          </p>
          <Link
            href="/create-fine-tune"
            className="bg-black hover:bg-gray-800 text-white font-bold py-3 px-6 rounded-full transition-colors duration-200 inline-block"
          >
            Create Your First AI Model
          </Link>
        </div>
      </section>

      {/* Content Sections */}
      <div className="bg-gray-100">
        {/* Video Placeholder Section */}
        <section className="py-16 bg-white">
          <div className="container mx-auto px-6">
            <h2 className="text-3xl font-bold mb-8 text-black text-center">
              See Photogen in Action
            </h2>
            <div className="w-full max-w-3xl mx-auto">
              <div className="w-full h-64 bg-gray-200 flex items-center justify-center">
                <span className="text-gray-500">Demo Video Placeholder</span>
              </div>
            </div>
          </div>
        </section>

        {/* Social Proof Section */}
        <section className="py-16 bg-gray-100">
          <div className="container mx-auto px-6">
            <h2 className="text-3xl font-bold mb-8 text-black text-center">
              Loved by Creators, Influencers, and Businesses Worldwide
            </h2>
            <div className="flex flex-col md:flex-row justify-center items-center space-y-6 md:space-y-0 md:space-x-6">
              {/* Twitter Testimonials */}
              <div className="w-full max-w-sm bg-white p-4 rounded shadow">
                <TwitterTweetEmbed tweetId="1840085947624632624" />
              </div>
              <div className="w-full max-w-sm bg-white p-4 rounded shadow">
                <TwitterTweetEmbed tweetId="1840085947624632624" />
              </div>
              <div className="w-full max-w-sm bg-white p-4 rounded shadow">
                <TwitterTweetEmbed tweetId="1840085947624632624" />
              </div>
            </div>
          </div>
        </section>

        {/* Old Way vs New Way Comparison Section */}
        <section className="py-16 bg-white">
          <div className="container mx-auto px-6 text-center">
            <h2 className="text-3xl font-bold mb-8 text-black">Content Creation is Changing...don't get left behind!</h2>
            <div className="flex flex-col md:flex-row items-stretch space-y-8 md:space-y-0 md:space-x-8">
              {/* Old Way */}
              <div className="md:w-1/2 bg-gray-100 p-6 rounded-lg flex flex-col items-center border-2 border-gray-300">
                <div className="w-full h-48 mb-4 flex items-center justify-center">
                  <Image 
                    src="/images/old.jpg" 
                    alt="Traditional Photography" 
                    width={300} 
                    height={200} 
                    objectFit="cover"
                    className="grayscale" // Add this line
                  />
                </div>
                <h3 className="text-2xl font-bold mb-2 text-black">The Old Way</h3>
                <h4 className="text-xl mb-2 text-black">Traditional Photography</h4>
                <p className="text-md mb-4 text-black">
                  Time-consuming, expensive, and resource-intensive
                </p>
                <ul className="list-disc list-inside marker:text-3xl text-center text-black space-y-4 text-xl flex-grow">
                  <li>Specific location needed</li>
                  <li>Large crew required</li>
                  <li>Expensive equipment</li>
                  <li>Time-consuming setup and editing</li>
                </ul>
              </div>
              {/* New Way */}
              <div className="md:w-1/2 bg-gray-100 p-6 rounded-lg flex flex-col items-center border-2 border-blue-500">
                <div className="w-full h-48 mb-4 flex items-center justify-center">
                  <Image src="/images/new.jpg" alt="AI-Powered Photography" width={300} height={200} objectFit="cover" />
                </div>
                <h3 className="text-2xl font-bold mb-2 text-black">
                  The New Way with Photogen
                </h3>
                <h4 className="text-xl mb-2 text-black">AI-Powered Creativity</h4>
                <p className="text-md mb-4 text-black">
                  Fast, affordable, and high-quality visuals
                </p>
                <ul className="list-disc list-inside marker:text-3xl text-center text-black space-y-4 text-xl flex-grow">
                  <li>Create images anywhere</li>
                  <li>One person, one laptop</li>
                  <li>No expensive equipment needed</li>
                  <li>World-class results in minutes</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Why Choose Photogen Section */}
        <section className="py-16 bg-white">
          <div className="container mx-auto px-6">
            <h2 className="text-3xl font-bold mb-8 text-black text-center">Why Choose Photogen?</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {/* Benefit 1 */}
              <div className="flex flex-col items-center">
                <div className="text-4xl mb-4">🌟</div>
                <h3 className="text-xl font-bold mb-2">High Quality Images Every Time</h3>
                <p className="text-base text-black text-center">
                  Create professional-grade visuals every time.
                </p>
              </div>
              {/* Benefit 2 */}
              <div className="flex flex-col items-center">
                <div className="text-4xl mb-4">⏱️</div>
                <h3 className="text-xl font-bold mb-2">Save Time</h3>
                <p className="text-base text-black text-center">
                  Generate photos in minutes, eliminating manual editing.
                </p>
              </div>
              {/* Benefit 3 */}
              <div className="flex flex-col items-center">
                <div className="text-4xl mb-4">🎨</div>
                <h3 className="text-xl font-bold mb-2">Creative Freedom</h3>
                <p className="text-base text-black text-center">
                  Customize AI models easily.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* How It Works Section */}
        <section id="how-it-works" className="py-16 bg-gray-100">
          <div className="container mx-auto px-6">
            <h2 className="text-3xl font-bold mb-8 text-black text-center">How It Works</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <div className="text-center">
                <div className="text-4xl mb-4">📸</div>
                <h3 className="text-xl font-bold mb-2 text-black">Upload Your Photos</h3>
                <p className="text-black">Upload a few photos of yourself to train the AI model.</p>
              </div>
              <div className="text-center">
                <div className="text-4xl mb-4">🤖</div>
                <h3 className="text-xl font-bold mb-2 text-black">AI Magic Happens</h3>
                <p className="text-black">Our AI processes your photos and creates a custom model.</p>
              </div>
              <div className="text-center">
                <div className="text-4xl mb-4">🎨</div>
                <h3 className="text-xl font-bold mb-2 text-black">Create Amazing Images</h3>
                <p className="text-black">Use your custom AI model to generate incredible images of yourself.</p>
              </div>
            </div>
          </div>
        </section>

        {/* Pricing Section */}
        <section id="pricing" className="py-16 bg-white">
          <div className="container mx-auto px-6">
            <h2 className="text-3xl font-bold mb-8 text-black text-center">Choose Your Plan</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              <SubscriptionPlan
                title="Basic Monthly"
                price="9.99"
                features={[
                  "100 AI-generated images per month",
                  "Basic editing tools",
                  "Email support"
                ]}
                link="https://buy.stripe.com/bIYaGjds25cTdkk8wy"
                userId={user?.id}
                userEmail={userEmail}
                yearly={false}
                className="transform scale-105 shadow-xl border-2 border-blue-500"
              />
              <SubscriptionPlan
                title="Basic Yearly"
                price="99.99"
                features={[
                  "100 AI-generated images per month",
                  "Basic editing tools",
                  "Email support",
                  "Save 17% compared to monthly"
                ]}
                link="https://buy.stripe.com/4gw9Cf3RseNt2FGaEH"
                userId={user?.id}
                userEmail={userEmail}
                yearly={true}
              />
              <SubscriptionPlan
                title="Premium Monthly"
                price="19.99"
                features={[
                  "500 AI-generated images per month",
                  "Advanced editing tools",
                  "Priority email support",
                  "Custom AI model training"
                ]}
                link="https://buy.stripe.com/eVag0DafQ7l1fss8wB"
                userId={user?.id}
                userEmail={userEmail}
                yearly={false}
              />
              <SubscriptionPlan
                title="Premium Yearly"
                price="199.99"
                features={[
                  "500 AI-generated images per month",
                  "Advanced editing tools",
                  "Priority email support",
                  "Custom AI model training",
                  "Save 17% compared to monthly"
                ]}
                link="https://buy.stripe.com/5kA6q3afQfRx0xy3cg"
                userId={user?.id}
                userEmail={userEmail}
                yearly={true}
              />
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section id="faq" className="py-16 bg-gray-100">
          <div className="container mx-auto px-6">
            <h2 className="text-3xl font-bold mb-8 text-black text-center">Frequently Asked Questions</h2>
            <div className="space-y-4">
              {/* FAQ Item 1 */}
              <details className="group bg-white">
                <summary className="flex justify-between items-center cursor-pointer p-4">
                  <span className="font-semibold">What is Photogen?</span>
                  <svg
                    className="w-6 h-6 transition-transform duration-200 group-open:rotate-180"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </summary>
                <div className="p-4 bg-gray-50">
                  <p className="text-gray-700">
                    Photogen is an AI-powered platform that allows users to create stunning photos and videos effortlessly.
                  </p>
                </div>
              </details>

              {/* FAQ Item 2 */}
              <details className="group bg-white">
                <summary className="flex justify-between items-center cursor-pointer p-4">
                  <span className="font-semibold">How does Photogen work?</span>
                  <svg
                    className="w-6 h-6 transition-transform duration-200 group-open:rotate-180"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </summary>
                <div className="p-4 bg-gray-50">
                  <p className="text-gray-700">
                    Upload your images, customize your AI models, and generate high-quality visuals in minutes.
                  </p>
                </div>
              </details>

              {/* Add more FAQ items as needed */}
            </div>
          </div>
        </section>

        {/* Final CTA Section */}
        <section className="py-16 bg-white">
          <div className="container mx-auto px-6 text-center">
            <h2 className="text-3xl font-bold mb-4 text-black">
              Ready to Create Stunning AI Visuals?
            </h2>
            <p className="text-lg mb-6 text-black">
              Click below to create your first AI model and bring your ideas to life!
            </p>
            <Link
              href="/create-fine-tune"
              className="bg-black text-white hover:bg-gray-800 font-bold py-3 px-6 rounded-full transition-colors duration-200 inline-block"
            >
              Create Your First AI Model
            </Link>
          </div>
        </section>
      </div>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-6">
        <div className="container mx-auto px-6 flex flex-col md:flex-row justify-between items-center">
          <div className="mb-4 md:mb-0">
            <Link href="/" className="text-xl font-bold">
              Photogen
            </Link>
          </div>
          <div className="flex space-x-4">
            <Link href="/#features" className="hover:text-gray-300">
              Features
            </Link>
            <Link href="/#how-it-works" className="hover:text-gray-300">
              How It Works
            </Link>
            <Link href="/#pricing" className="hover:text-gray-300">
              Pricing
            </Link>
            <Link href="/#faq" className="hover:text-gray-300">
              FAQ
            </Link>
            <Link href="/#contact" className="hover:text-gray-300">
              Contact
            </Link>
          </div>
          <div className="mt-4 md:mt-0">
            <p className="text-sm">&copy; {new Date().getFullYear()} Photogen. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}