"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import Image from "next/image";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import BackgroundImageGrid from "../src/components/BackgroundImageGrid";

const Background3D = dynamic(() => import("../src/components/Background3D"), {
  ssr: false,
});
const Hero = dynamic(() => import("../src/components/Hero"), { ssr: false });

export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen bg-black relative">
      <Canvas className="absolute inset-0 z-0 mt-[-150px]">
        <Background3D />
        <OrbitControls enableZoom={false} />
      </Canvas>
      <div className="relative z-10 h-screen flex items-center justify-center">
        <Hero />
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
          <div className="container mx-auto px-5 mt-[100px] flex flex-col md:flex-row items-center">
            <div className="w-full md:w-[70%] pr-0 md:pr-8 flex flex-col justify-center items-center text-center pointer-events-auto">
              <div className="bg-white bg-opacity-40 p-6 rounded-lg shadow-md">
                <h1 className="text-4xl md:text-5xl font-bold mb-8 text-white shadow-text">
                  Throw away your Camera – Let AI Capture Your World!
                </h1>
                <p className="text-lg md:text-xl mb-6 text-gray-200 shadow-text">
                  Revolutionize your memories with Photogen, powered by
                  state-of-the-art models and crafted by two AI enthusiasts. Say
                  goodbye to tedious photo shoots and hello to breathtaking
                  images and videos, all generated by AI right from your device.
                </p>
                <div className="flex flex-wrap justify-center gap-4">
                  <Link
                    href="/flux_pro"
                    className="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition-colors duration-200"
                  >
                    Create AI Photo
                  </Link>
                  <Link
                    href="/style-model"
                    className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition-colors duration-200"
                  >
                    Style Virtual Model
                  </Link>
                  <Link
                    href="/create-video"
                    className="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded transition-colors duration-200"
                  >
                    Create AI Video
                  </Link>
                </div>
              </div>
            </div>
            <div className="w-full md:w-[30%] flex items-center justify-center pointer-events-auto mt-8 md:mt-0">
              <form className="space-y-4 w-full max-w-sm bg-white bg-opacity-40 p-6 rounded-lg shadow-md">
                <input
                  type="text"
                  placeholder="Username"
                  className="w-full p-2 border rounded bg-gray-800 text-white"
                />
                <input
                  type="password"
                  placeholder="Password"
                  className="w-full p-2 border rounded bg-gray-800 text-white"
                />
                <button
                  type="submit"
                  className="w-full bg-blue-500 text-white p-2 rounded hover:bg-blue-600 transition-colors"
                >
                  Log In
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>

      {/* Testimonials Section with Background Image Grid */}
      <div className="relative">
        <div className="absolute inset-0 z-0 w-full h-full">
          <BackgroundImageGrid />
        </div>

        {/* Testimonials Section */}
        <div className="relative z-10 bg-black bg-opacity-50 py-20">
          <div className="container mx-auto px-5 relative z-10">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <div className="bg-white p-6 rounded-lg shadow-md">
                <p className="text-lg mb-4 text-black">
                  "Photogen has revolutionized my Instagram game! I can create
                  stunning, professional-looking photos in minutes. It's like
                  having a personal photographer in my pocket!"
                </p>
                <p className="font-bold text-black">- Sarah J., Influencer</p>
              </div>
              <div className="bg-white p-6 rounded-lg shadow-md">
                <p className="text-lg mb-4 text-black">
                  "As a small business owner, Photogen has been a game-changer
                  for my product photography. I've saved so much time and money,
                  and my sales have increased thanks to the high-quality
                  images."
                </p>
                <p className="font-bold text-black">
                  - Mike T., E-commerce Entrepreneur
                </p>
              </div>
              <div className="bg-white p-6 rounded-lg shadow-md">
                <p className="text-lg mb-4 text-black">
                  "I'm not a professional photographer, but Photogen makes me
                  feel like one. It's incredibly easy to use, and the results
                  are always impressive. My family photos have never looked
                  better!"
                </p>
                <p className="font-bold text-black">
                  - Emily R., Hobbyist Photographer
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Empty space to extend the background image grid */}
        <div className="h-40"></div>
      </div>

      {/* Why Choose Photogen Section */}
      <div className="relative z-10 bg-black text-white py-20">
        <div className="container mx-auto px-5">
          <h2 className="text-3xl md:text-4xl font-bold mb-8">
            Why Choose Photogen?
          </h2>
          <p className="text-lg md:text-xl mb-6">
            Photogen offers cutting-edge AI models to help you create stunning
            photos and videos effortlessly. Our models are trained on diverse
            datasets to ensure high-quality results for any type of image or
            video you want to create.
          </p>
          <p className="text-lg md:text-xl mb-6">
            Whether you're a professional content creator or just someone who
            loves capturing memories, Photogen has the tools you need to bring
            your vision to life.
          </p>
        </div>
      </div>

      {/* Static Footer */}
      <footer className="bg-gray-900 text-white py-6 relative z-10">
        <div className="container mx-auto px-5 flex flex-col md:flex-row justify-between items-center">
          <p className="mb-4 md:mb-0">An Amoeba Labs Experiment</p>
          <p className="text-sm italic max-w-md text-center md:text-right">
            &ldquo;Knowledge is knowing that Frankenstein is not the monster.
            Wisdom is knowing that he is.&rdquo;
          </p>
        </div>
      </footer>
    </div>
  );
}
